version: "3"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-CU18-ubuntu-20.04
    container_name: mssql-ucommerce-test
    ports:
    - 14311:1433
    environment:
    - ACCEPT_EULA=Y
    - MSSQL_PID=Developer
    - SA_PASSWORD=MSSqlDev22